"""Write SYNTHETIC smoke-test examples to data/examples/smoke/{train,val}.jsonl.

These are NOT real ERCOT data: random errors and a made-up prompt in the DATA_CONTRACT format,
used only to test the verifiers env and the prime-rl pipeline before the real dataset exists.
Every id starts with "SYNTH-", split is "smoke-*", and meta.synthetic is true.

    /hackathon/prime-rl/.venv/bin/python scripts/make_smoke_examples.py
"""

from __future__ import annotations

import json
import random
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "examples" / "smoke"
ZONES = ["coast", "east", "far_west", "north", "north_central", "south", "south_central", "west"]
HOURS = [16, 17, 18, 19, 20]
Z90 = 1.2816  # N(0,1) 90th percentile

SYSTEM = (
    "You forecast how wrong ERCOT's day-ahead load forecast will be. For each listed hour-ending (HE), "
    "give the 10th, 50th and 90th percentiles of the error (actual load minus ERCOT forecast) in MW.\n"
    'Reply with JSON only: {"hours":[{"he":16,"p10":-850,"p50":120,"p90":1400}, ...]} with one entry per '
    "listed hour and p10 <= p50 <= p90."
)


def make_example(rng: random.Random, zone: str, day: date, split: str) -> dict:
    clim_sigma = rng.uniform(150, 900)  # "historical" spread for this zone/season
    volatile = rng.random() < 0.25
    day_sigma = clim_sigma * (rng.uniform(1.5, 3.0) if volatile else rng.uniform(0.3, 0.9))
    bias = rng.gauss(0, 0.3 * day_sigma)
    spread = day_sigma * rng.uniform(0.2, 0.6)  # fake "model spread" signal, correlated with day_sigma
    baseline, actual, lines = {}, {}, []
    for h in HOURS:
        base = {"p10": round(-Z90 * clim_sigma), "p50": 0.0, "p90": round(Z90 * clim_sigma)}
        baseline[str(h)] = base
        actual[str(h)] = round(bias + rng.gauss(0, day_sigma), 1)
        lines.append(f"HE{h}: baseline p10={base['p10']:.0f} p50={base['p50']:.0f} p90={base['p90']:.0f} MW")
    afd = (
        "Forecast confidence is LOW: a dryline/front timing is uncertain and storms may reduce afternoon temps."
        if volatile
        else "High confidence: persistent ridge, hot and dry, little day-to-day change."
    )
    user = (
        "[SYNTHETIC SMOKE-TEST EXAMPLE - not real data]\n"
        f"Weather zone: {zone}\nOperating day: {day.isoformat()}\n"
        f"ERCOT load-model spread (max-min across models, peak hours): {spread:.0f} MW\n"
        f"NWS forecaster discussion (excerpt): {afd}\n"
        "Numeric baseline percentiles of the error:\n" + "\n".join(lines) + "\n"
        f"Hours to forecast: {HOURS}"
    )
    return {
        "id": f"SYNTH-{day.isoformat()}_{zone}",
        "zone": zone,
        "operating_date": day.isoformat(),
        "split": split,
        "hours": HOURS,
        "prompt": [{"role": "system", "content": SYSTEM}, {"role": "user", "content": user}],
        "baseline": baseline,
        "actual_error": actual,
        "meta": {"synthetic": True, "volatile": volatile, "model_spread_mw": round(spread, 1)},
    }


def main() -> None:
    rng = random.Random(1234)
    OUT.mkdir(parents=True, exist_ok=True)
    for split, start, n_days in (("train", date(2024, 6, 1), 8), ("val", date(2024, 9, 1), 2)):
        rows = [
            make_example(rng, zone, start + timedelta(days=d), f"smoke-{split}")
            for d in range(n_days)
            for zone in ZONES
        ]
        path = OUT / f"{split}.jsonl"
        path.write_text("".join(json.dumps(r) + "\n" for r in rows))
        print(f"wrote {len(rows)} synthetic examples -> {path}")
    (OUT / "README.txt").write_text(
        "SYNTHETIC smoke-test data generated by scripts/make_smoke_examples.py. Not real ERCOT data.\n"
    )


if __name__ == "__main__":
    main()
